# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3774978635e801930a6c657807555fdb02e77370d05e8dfad6a50d905620184c8a3826b95e8866bf80f97308e5593dd7d64b9b352162d5afe38b271911523733

test:
  secret_key_base: 09cb6739a2c742040c30f49f6df2b53da53825dca9345407383b6dc82cbea3faef40572a6ef7f58d9634835c67d1eb4849beb1be3bbb735f5ebe4d29db8ea49a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
